package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.rs_userinfo;
import hello.Rs_UserInfoRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private Rs_UserInfoRepository rs_userinfoRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUserInfo (@RequestParam String username
			, @RequestParam String mobilephone) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		rs_userinfo n = new rs_userinfo();
		n.setUserName(username);
		n.setMobilePhone(mobilephone);
		rs_userinfoRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<rs_userinfo> getAllUsers() {
		// This returns a JSON or XML with the users
		return rs_userinfoRepository.findAll();
	}
}